---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cameras-0001
  namespace: default
spec:
  repo: https://teknoir.github.io/boxer-helm
  chart: boxer
  targetNamespace: default
  version: 0.4.1
  valuesContent: |-
    nvr:
      defaults:
        image:
          # Running on Jetson Orin
          tag: ds7-gst1.24.7-l4t

        camera:
          #pipeline: rtspsrc protocols=tcp timeout=10000000 location={{.uri}} latency=1000 ! queue ! rtpjitterbuffer latency=1500 ! queue ! rtph264depay ! queue ! nvv4l2decoder ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=3840,height=2160 ! queue ! m.sink_0 nvstreammux name=m batch-size=4 width=3840 height=2160 ! nvinferserver name=nvis config-file-path=/models/rtdetr_config.pbtxt unique-id=2 interval=5 ! nvinferserver config-file-path=/models/up_down_classifier_config.pbtxt unique-id=5 ! nvtracker tracker-width=640 tracker-height=384 ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/models/config_tracker_NvDeepSORT.yml compute-hw=2 gpu-id=0 ! queue ! nvstreamdemux name=d d.src_0 ! queue ! tee name=tee2 tee2. ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=[1,1920],height=[1,1080],pixel-aspect-ratio=1/1 ! nvjpegenc quality=55 ! appsink sync=0 name=mqttsink tee2. ! queue ! nvvideoconvert compute-hw=GPU ! video/x-raw,format=RGB,width=[1,640],height=[1,360],pixel-aspect-ratio=1/1 ! queue ! motioncells threshold=0.00005 gridx=32 gridy=18 ! fakesink tee2. ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 ! nvvideoconvert ! queue ! nvv4l2h264enc iframeinterval=10 ! queue ! h264parse ! queue ! splitmuxsink sink=nvdsfilesink muxer-properties=properties,streamable=true location=/app/videos/{{.camera_id}}_%05d.mp4 max-size-time=15000000000 max-files=160
          #pipeline: rtspsrc protocols=tcp timeout=10000000 location={{.uri}} latency=1000 ! queue ! rtpjitterbuffer latency=1500 ! queue ! rtph264depay ! queue ! nvv4l2decoder ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=3840,height=2160 ! queue ! m.sink_0 nvstreammux name=m batch-size=4 width=3840 height=2160 ! nvinferserver name=nvis config-file-path=/models/rtdetr_config.pbtxt unique-id=2 interval=5 ! nvinferserver config-file-path=/models/up_down_classifier_config.pbtxt unique-id=5 ! nvtracker tracker-width=640 tracker-height=384 ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/models/config_tracker_NvDeepSORT.yml compute-hw=2 gpu-id=0 ! queue ! nvstreamdemux name=d d.src_0 ! queue ! tee name=tee2 tee2. ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=[1,1920],height=[1,1080],pixel-aspect-ratio=1/1 ! nvjpegenc quality=55 ! appsink sync=0 name=mqttsink tee2. ! queue ! nvvideoconvert compute-hw=GPU ! video/x-raw,format=RGB,width=[1,640],height=[1,360],pixel-aspect-ratio=1/1 ! queue ! motioncells threshold=0.00005 gridx=32 gridy=18 ! fakesink tee2. ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 ! nvvideoconvert ! queue ! nvv4l2h264enc iframeinterval=150 insert-sps-pps=1 profile=2 level=4.0 bitrate=4000000 ! h264parse config-interval=1 ! queue ! splitmuxsink sink=nvdsfilesink muxer-properties=properties,streamable=true,moov-relocation=true location=/app/videos/{{.camera_id}}_%05d.mp4 max-size-time=15000000000 max-files=160
          #pipeline: rtspsrc protocols=tcp timeout=10000000 location={{.uri}} latency=1000 ! queue ! rtpjitterbuffer latency=1500 ! queue ! rtph264depay ! queue ! nvv4l2decoder ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=3840,height=2160 ! queue ! m.sink_0 nvstreammux name=m batch-size=4 width=3840 height=2160 ! nvinferserver name=nvis config-file-path=/models/rtdetr_config.pbtxt unique-id=2 interval=5 ! nvinferserver config-file-path=/models/up_down_classifier_config.pbtxt unique-id=5 ! nvtracker tracker-width=640 tracker-height=384 ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/models/config_tracker_NvDeepSORT.yml compute-hw=2 gpu-id=0 ! queue ! nvstreamdemux name=d d.src_0 ! queue ! tee name=tee2 tee2. ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=[1,1920],height=[1,1080],pixel-aspect-ratio=1/1 ! nvjpegenc quality=55 ! appsink sync=0 name=mqttsink tee2. ! queue ! nvvideoconvert compute-hw=GPU ! video/x-raw,format=RGB,width=[1,640],height=[1,360],pixel-aspect-ratio=1/1 ! queue ! motioncells threshold=0.00005 gridx=32 gridy=18 ! fakesink tee2. ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 ! nvvideoconvert ! queue ! nvv4l2h264enc iframeinterval=10 ! queue ! h264parse ! queue ! splitmuxsink sink=nvdsfilesink muxer-properties=properties,streamable=true location=/app/videos/{{.camera_id}}_%05d.mp4 max-size-time=15000000000 max-files=160
          #pipeline: rtspsrc protocols=tcp timeout=10000000 location={{.uri}} latency=1000 ! queue ! rtpjitterbuffer latency=1500 ! queue ! rtph264depay ! queue ! nvv4l2decoder ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=3840,height=2160 ! queue ! m.sink_0 nvstreammux name=m batch-size=4 width=3840 height=2160 ! nvinferserver name=nvis config-file-path=/models/rtdetr_config.pbtxt unique-id=2 interval=5 ! nvinferserver config-file-path=/models/up_down_classifier_config.pbtxt unique-id=5 ! nvtracker tracker-width=640 tracker-height=384 ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/models/config_tracker_NvDeepSORT.yml compute-hw=2 gpu-id=0 ! queue ! nvstreamdemux name=d d.src_0 ! queue ! tee name=tee2 tee2. ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=[1,1920],height=[1,1080],pixel-aspect-ratio=1/1 ! nvjpegenc quality=55 ! appsink sync=0 name=mqttsink tee2. ! queue ! nvvideoconvert compute-hw=GPU ! video/x-raw,format=RGB,width=[1,640],height=[1,360],pixel-aspect-ratio=1/1 ! queue ! motioncells threshold=0.00005 gridx=32 gridy=18 ! fakesink tee2. ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 ! nvvideoconvert ! queue ! nvv4l2h264enc iframeinterval=10 ! queue ! h264parse ! queue ! splitmuxsink sink=nvdsfilesink muxer-properties=properties,streamable=true location=/app/videos/{{.camera_id}}_%05d.mp4 max-size-time=15000000000 max-files=160
          pipeline: rtspsrc protocols=tcp timeout=10000000 location={{.uri}} latency=1000 ! queue ! rtpjitterbuffer latency=1500 ! queue ! rtph264depay ! queue ! nvv4l2decoder ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=3840,height=2160 ! queue ! m.sink_0 nvstreammux name=m batch-size=4 width=3840 height=2160 ! nvinferserver name=nvis config-file-path=/models/rtdetr_config.pbtxt unique-id=2 interval=5 ! nvinferserver config-file-path=/models/up_down_classifier_config.pbtxt unique-id=5 ! nvtracker tracker-width=640 tracker-height=384 ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/models/config_tracker_NvDeepSORT.yml compute-hw=2 gpu-id=0 ! queue ! nvstreamdemux name=d d.src_0 ! queue ! tee name=tee2 tee2. ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=[1,1920],height=[1,1080],pixel-aspect-ratio=1/1 ! nvjpegenc quality=55 ! appsink sync=0 name=mqttsink tee2. ! queue ! nvvideoconvert compute-hw=GPU ! video/x-raw,format=RGB,width=[1,640],height=[1,360],pixel-aspect-ratio=1/1 ! queue ! motioncells threshold=0.00005 gridx=32 gridy=18 ! fakesink tee2. ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 ! nvvideoconvert ! queue ! nvv4l2h264enc insert-sps-pps=1 insert-vui=1 idrinterval=30 iframeinterval=30 ! queue ! h264parse ! queue ! splitmuxsink sink=nvdsfilesink muxer-properties=properties,streamable=true location=/app/videos/{{.camera_id}}_%05d.mp4 max-size-time=15000000000 max-files=160

        motion:
          activeInterval: 15
    
        # Deprecated in favor of ORG TREE
        location:
          country: "us"
          region: "south"
          branch: "houston"
          facility: "720 n. post oak"
          site: "exterior"
          zone: "parking lot"
          group: "poc"
    
      #Max 8 cameras on Orin for now...
      instances:
        # nvr-garage-store-room-205
        - name: npostoak-garage-store-room
          camera:
            uri: rtsp://admin:c2h0e0v4y!@172.18.0.205:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1

        # nvr-garage-ramp-north-207
        - name: npostoak-garage-ramp-north
          camera:
            uri: rtsp://admin:c2h0e0v4y!@172.18.0.207:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
        
        # nvr-garage-ramp-south-208
        - name: npostoak-garage-ramp-south
          camera:
            uri: rtsp://admin:c2h0e0v4y!@172.18.0.208:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
        
        # nvr-parking-surface-north-209
        - name: npostoak-parking-surface-north
          camera:
            uri: rtsp://admin:c2h0e0v4y!@172.18.0.209:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1

        # nvr-parking-surface-south-210
        #- name: npostoak-parking-surface-south
        #  camera:
        #    uri: rtsp://admin:c2h0e0v4y!@172.18.0.210:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1

        # nvr-front-parking-north-211
        - name: npostoak-front-parking-north
          camera:
            uri: rtsp://admin:c2h0e0v4y!@172.18.0.211/media/video2

        # nvr-rear-parking-north-212
        - name: npostoak-rear-parking-north
          camera:
            uri: rtsp://admin:c2h0e0v4y!@172.18.0.212/media/video2

        # nvr-front-parking-south-213
        - name: npostoak-front-parking-south
          camera:
            uri: rtsp://admin:c2h0e0v4y!@172.18.0.213/media/video2
        
        # nvr-rear-parking-south-214
        #- name: npostoak-rear-parking-south
        #  camera:
        #    uri: rtsp://admin:c2h0e0v4y!@172.18.0.214/media/video2

    observatory-pipeline:
      defaults:
        debugLevel: DEBUG
        
        labels:
          deviceID: "npostoak-exterior"
          namespace: "boxer-property"
          domain: "teknoir.cloud"

      streams:
        - stream: update-frame-rate-control
        - stream: record-detections
        - stream: update-movements
        # ALERTS
        #- stream: motion
        - stream: loitering
        - stream: person-down
        - stream: catalytic-theft
        - stream: line-crossing
        # ALERT PROCESSING
        - stream: update-alerts
      file-transfer:
        defaults:
          debugLevel: DEBUG

          labels:
            deviceID: "npostoak-exterior"
            namespace: "boxer-property"
            domain: "teknoir.cloud"
    
        streams:
          - stream: transfer-file
            video:
              mountSegmentPath: true
              mountClipTempPath: true
          - stream: prepare-file
            debugLevel: DEBUG
            video:
              mountSegmentPath: true
              mountClipTempPath: true

      keydb:
        image:
          # The Orin is an ARM64 device
          tag: "arm64_v6.3.4"
