nvr:
  defaults:
    # Deprecated in favor of ORG TREE
    location:
      country: "us"
      region: "south"
      branch: "houston"
      facility: "7676 hillmont st"
      site: "interior"
      zone: "entrance"
      group: "production"
  instances:
    - name: hillmont-7676-rear-door
      camera:
        uri: rtsp://admin:12345@172.18.156.239:554/media/video1
      location:
        zone: "entrance"
    - name: hillmont-7676-west-stair
      camera:
        uri: rtsp://admin:12345@172.18.156.235:554/media/video1
      location:
        zone: "entrance"
    - name: hillmont-7676-east-stair
      camera:
        uri: rtsp://admin:12345@172.18.156.234:554/media/video1
      location:
        zone: "entrance"
    - name: hillmont-7676-elevators
      camera:
        uri: rtsp://admin:12345@172.18.156.233:554/media/video1
      location:
        zone: "elevators"
    - name: hillmont-7676-2nd-floor-stair-a
      camera:
        uri: rtsp://admin:c2h0e0v4y@172.18.156.251:554/media/video1
      location:
        zone: "stairs"
    - name: hillmont-7676-floor3-stair_freight-lobby
      camera:
        uri: rtsp://admin:c2h0e0v4y@172.18.156.246:554/media/video1
      location:
        zone: "lobby"
    - name: hillmont-7676-3rd-floor-stair-b
      camera:
        uri: rtsp://admin:c2h0e0v4y@172.18.156.249:554/media/video1
      location:
        zone: "stairs"
    - name: hillmont-7676-2nd-floor-front-stairs
      camera:
        uri: rtsp://admin:c2h0e0v4y@172.18.156.250:554/media/video1
      location:
        zone: "stairs"
    - name: hillmont-7676-3rd-floor-ele-lobby
      camera:
        uri: rtsp://admin:c2h0e0v4y@172.18.156.248:554/media/video1
      location:
        zone: "lobby"
    - name: hillmont-7676-2nd-floor-ele-lobby
      camera:
        uri: rtsp://admin:c2h0e0v4y@172.18.156.252:554/media/video1
      location:
        zone: "lobby"
    - name: hillmont-7676-3rd-floor-stair-a
      camera:
        uri: rtsp://admin:c2h0e0v4y@172.18.156.253:554/media/video1
      location:
        zone: "stairs"
    - name: hillmont-7676-front-door
      camera:
        uri: rtsp://admin:12345@172.18.156.231:554/media/video1
      location:
        zone: "entrance"
    - name: hillmont-7676-2nd-floor-stair-b
      camera:
        uri: rtsp://admin:c2h0e0v4y@172.18.156.247:554/media/video1
      location:
        zone: "lobby"
    - name: hillmont-7676-floor2-stair-freight-lobby
      camera:
        uri: rtsp://admin:c2h0e0v4y@172.18.156.254:554/media/video1
      location:
        zone: "lobby"
    - name: hillmont-7676-main-entrance
      camera:
        uri: rtsp://admin:12345@172.18.156.243:554/media/video2
        # Resolution 1600x1200
        pipeline: rtspsrc location={{.uri}} latency=1000 ! queue ! rtpjitterbuffer latency=250 ! queue ! rtph264depay ! queue ! nvv4l2decoder gpu-id=0 ! queue ! nvvideoconvert gpu-id=0 ! video/x-raw(memory:NVMM),width=1600,height=1200 ! queue ! m.sink_0 nvstreammux name=m batch-size=4 width=1600 height=1200 gpu-id=0 ! queue ! nvinferserver name=nvis config-file-path=/models/rtdetr_config.pbtxt unique-id=2 interval=15 ! queue ! nvinferserver config-file-path=/models/up_down_classifier_config.pbtxt unique-id=5 ! queue ! nvtracker tracker-width=640 tracker-height=384 gpu-id=0 ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/models/config_tracker_NvDeepSORT.yml compute-hw=2 ! nvstreamdemux name=d d.src_0 ! queue ! tee name=t t. ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 ! nvv4l2h265enc copy-meta=true iframeinterval=15 bitrate=250000 ! queue ! h265parse ! queue ! splitmuxsink sink=nvdsfilesink muxer-properties=properties,streamable=true location=/app/videos/{{.camera_id}}_%05d.mp4 max-size-time=15000000000 max-files=5760 t. ! queue ! nvdsanalytics config-file=/app/config/config_nvdsanalytics.txt ! queue ! nvdsosd ! nvvideoconvert ! video/x-raw(memory:NVMM),width=[1,1920],height=[1,1080],pixel-aspect-ratio=1/1 ! nvvideoconvert ! queue ! nvjpegenc quality=45 ! appsink sync=0 name=mqttsink t. ! nvvideoconvert ! video/x-raw,format=RGB,width=[1,640],height=[1,360],pixel-aspect-ratio=1/1 ! nvvideoconvert ! motioncells threshold=0.00005 gridx=32 gridy=18 ! fakesink
      location:
        zone: "entrance"

observatory-pipeline:
  defaults:
    labels:
      deviceID: "hillmont-l4"

  streams:
    - stream: update-frame-rate-control
      mqtt:
        topicDetections: "camera/frames/#"
    - stream: record-detections
      mqtt:
        topicDetections: "camera/frames/#"
    - stream: update-movements
    - stream: filter-movements
    # ALERTS
    - stream: motion
    - stream: loitering
    - stream: person-down
    - stream: catalytic-theft
    # ALERT PROCESSING
    - stream: update-alerts
    - stream: make-clip
      video:
        mountSegmentPath: true
        mountClipTempPath: true